// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DTOs;
public class TransactionDto
{
    public Guid Id { get; set; }

    public Guid PaymentId { get; set; }

    public string TransactionRef { get; set; }

    public string GatewayResponse { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}