// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class CommentLike
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public Guid CommentId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Comment Comment { get; set; }

    public virtual User User { get; set; }
}