// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Transaction
{
    public Guid Id { get; set; }

    public Guid OrderId { get; set; }

    public string TxnRef { get; set; }

    public decimal? Amount { get; set; }

    public string BankCode { get; set; }

    public string CardType { get; set; }

    public DateTime? PayDate { get; set; }

    public string ResponseCode { get; set; }

    public string TransactionStatus { get; set; }

    public string SecureHash { get; set; }

    public string RawData { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Order Order { get; set; }
}